services:
  - type: web
    name: rahal-api-portal
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.1
      - key: PORT
        value: 10000
    healthCheckPath: /api/captcha/generate
    autoDeploy: true
