/**
 * POST /api/mock-rahal-backend/flights/search
 * ─────────────────────────────────────────────────────────────────────────
 * Plays the RAHAL side of the exchange, entirely within this same
 * Render deployment — no real airline system involved. This exists
 * purely so the sign→encrypt outbound / decrypt→verify inbound
 * pipeline can be exercised end-to-end and observed, without pointing
 * anything at stafftravel.qatarairways.com.qa or rahal.qatarairways.com.qa.
 *
 * Receives: { encryptedKey, iv, authTag, ciphertext, signature }
 *   - decrypts using the mock-RAHAL encryption PRIVATE key
 *   - verifies the signature using OUR (the caller's) signing PUBLIC key
 * Responds: same envelope shape, but encrypted with OUR encryption
 * PUBLIC key and signed with the mock-RAHAL signing PRIVATE key — the
 * mirror image of what we sent, proving both directions work.
 * ─────────────────────────────────────────────────────────────────────────
 */
const { keys, decryptWith, verifyWith, encryptFor, signWith } = require('../../../../lib/security/demoCrypto');

export default function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ code: 'METHOD_NOT_ALLOWED', message: 'Use POST' });

  const { signature, ...envelope } = req.body || {};
  if (!signature || !envelope.ciphertext) {
    return res.status(422).json({ code: 'VALIDATION_ERROR', message: 'Expected a signed+encrypted envelope: { encryptedKey, iv, authTag, ciphertext, signature }.' });
  }

  let decrypted;
  try {
    decrypted = decryptWith(keys.mockRahalEncryption.privateKey, envelope);
  } catch (err) {
    return res.status(400).json({ code: 'DECRYPTION_FAILED', message: 'Could not decrypt payload: ' + err.message });
  }

  const signatureValid = verifyWith(keys.ourSigning.publicKey, decrypted, signature);
  if (!signatureValid) {
    return res.status(401).json({ code: 'SIGNATURE_INVALID', message: 'Signature verification failed — payload may have been tampered with, or was signed with the wrong key.' });
  }

  // ── "RAHAL" processes the request and builds a real-shaped response ──
  const responsePayload = {
    searchId: 'srch_demo_' + Math.random().toString(36).slice(2, 10),
    outboundOptions: [{
      flightOptionId: 'FLT_OPT_QR007_DEMO',
      flightNumber: 'QR007',
      origin: decrypted.origin || 'DOH',
      destination: decrypted.destination || 'LHR',
      departureDateTime: (decrypted.departureDate || '2026-09-15') + 'T08:30:00Z',
      staffSeatsAvailable: 4,
      fareSummary: { ticketType: decrypted.ticketType || 'ID90', totalAmount: 123.50, currency: 'QAR' },
    }],
    _mockNotice: 'This response was generated by the local mock-rahal-backend route, not a real Qatar Airways system.',
  };

  const responseEnvelope = encryptFor(keys.ourEncryption.publicKey, responsePayload);
  const responseSignature = signWith(keys.mockRahalSigning.privateKey, responsePayload);

  return res.status(200).json({ ...responseEnvelope, signature: responseSignature });
}
